### ISSUE TITLE
[질문]Lab 실의 IDE 가 안떠요

### ISSUE THREAD

**Issue by Global783** [Global783/skccCloudApp#1]

**Comment by Global783** [comment]
크롬으로 사용해 주시길 바랍니다.
크롬이 텝이 여러개가 떠있다면 브라우저 메모리 부족으로 안뜰수가 있습니다. 기타 브라우저를 중지하신 후에 다시한번 새로고침 해주세요.

브라우저에서 쿠키사용을 막았을때 IDE 가 보여지지가 않습니다. 브라우저 설정에서 쿠키 설정을 전체 허용으로 놓아주시길 바랍니다. 자세한 내용은 아래 동영상에 5분50초 부분부터 보시면 됩니다.
https://youtu.be/aKcZVGXFwpI

**Comment by pooroom** [comment]
Hey, guys
